<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'admin' })
const API_URL = 'http://localhost:8000'; const categories = ref<any[]>([]); const loading = ref(true); const selectedCategory = ref<any | null>(null); const saving = ref(false); const errorMessage = ref('')
const load = async () => { loading.value = true; try { categories.value = await $fetch<any[]>(`${API_URL}/categories`) } finally { loading.value = false } }
const remove = async (id: string | number) => { if (!confirm('Delete this category?')) return; await $fetch(`${API_URL}/categories/${id}`, { method: 'DELETE' }); await load() }
const openAddCategory = () => { selectedCategory.value = {}; }
const openEditCategory = (category: any) => { selectedCategory.value = category; }
const saveCategory = async (category: any) => { saving.value = true; errorMessage.value = ''; try { const id = selectedCategory.value?.id; await $fetch(`${API_URL}/categories${id ? `/${id}` : ''}`, { method: id ? 'PUT' : 'POST', body: category }); selectedCategory.value = null; await load() } catch { errorMessage.value = id ? 'Unable to update category.' : 'Unable to create category.' } finally { saving.value = false } }
onMounted(load)
</script>
<template><section><AdminHeader title="Categories" description="Organize your catalog with clear categories." action-label="Add category" @action="openAddCategory" /><p v-if="errorMessage" class="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ errorMessage }}</p><div v-if="loading" class="py-20 text-center text-sm text-gray-500">Loading categories...</div><div v-else class="overflow-hidden rounded-2xl border border-[#d9e7e2] bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-[560px] w-full"><thead class="bg-[#f3f9f7] text-left text-[10px] font-bold uppercase tracking-[0.16em] text-gray-500"><tr><th class="px-5 py-4">Name</th><th class="px-5 py-4">Slug</th><th class="px-5 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-[#e6efec]"><tr v-for="category in categories" :key="category.id"><td class="px-5 py-4 font-semibold text-ink">{{ category.name }}</td><td class="px-5 py-4 text-sm text-gray-500">{{ category.slug }}</td><td class="px-5 py-4 text-right text-sm"><button class="mr-3 font-semibold text-primary" @click="openEditCategory(category)">Edit</button><button class="font-semibold text-red-600" @click="remove(category.id)">Delete</button></td></tr></tbody></table></div><p v-if="!categories.length" class="p-10 text-center text-sm text-gray-500">No categories yet.</p></div><AdminCategoryForm v-if="selectedCategory" :key="selectedCategory.id || 'new'" :category="selectedCategory.id ? selectedCategory : null" :saving="saving" @save="saveCategory" @close="selectedCategory = null" /></section></template>
